version: "3"

services:
  srv-admin:
    build: srv-admin
    command: python manage.py runserver 0.0.0.0:8000
    env_file: srv-admin/.env
    volumes:
      - ./srv-admin/manage.py:/opt/dit-app/manage.py
      - ./srv-admin/.env:/opt/demo-app/.env
      - ./srv-admin/pytest.ini:/opt/demo-app/pytest.ini
      - ./srv-admin/src/:/opt/dit-app/src/
      - ./srv-admin/static/:/var/www/static/
      - ./srv-admin/media/:/var/www/media/
      - ./import/:/opt/demo-app/import/
    ports:
      - "8000:8000"
    depends_on:
      - srv-db

  srv-db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./backups/:/backups/
      - ./import/:/import/
    ports:
      - "5432:5432"

  # srv-webapp:
  #   build: srv-webapp
  #   command: yarn dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./srv-webapp/:/usr/src/app/
  #   depends_on:
  #     - srv-db
  #     - srv-admin
