# Generated by Django 3.1.2 on 2020-11-19 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_local', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
