# Generated by Django 3.1.5 on 2021-08-31 11:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication_local', '0005_create_base_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='token',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='code'),
        ),
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('token', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='code')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('contract_id', models.CharField(max_length=256)),
                ('principal_id', models.CharField(max_length=256)),
                ('target_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
