# Generated by Django 3.1.5 on 2021-05-19 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defect', '0001_initial'),
        ('real_estate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteddefect',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defect_reporteddefect_related', related_query_name='defect_reporteddefects', to='real_estate.contract', verbose_name='Vertrag'),
        ),
        migrations.AddField(
            model_name='reporteddefect',
            name='defect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_reporteddefect_related', related_query_name='defect_reporteddefects', to=settings.DEFECT_DEFECT_MODEL, verbose_name='Defect'),
        ),
        migrations.AddField(
            model_name='reporteddefect',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defect_reporteddefect_related', related_query_name='defect_reporteddefects', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='defecttype',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='defect_defecttype_related', related_query_name='defect_defecttypes', to=settings.DEFECT_AREA_MODEL, verbose_name='Areas'),
        ),
        migrations.AddField(
            model_name='defecttype',
            name='visible_groups',
            field=models.ManyToManyField(blank=True, related_name='defect_defecttype_related', related_query_name='defect_defecttypes', to='auth.Group', verbose_name='Visible groups'),
        ),
        migrations.AddField(
            model_name='defectresolutionrating',
            name='reported_defect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defect_defectresolutionrating_related', related_query_name='defect_defectresolutionratings', to=settings.DEFECT_REPORTEDDEFECT_MODEL, verbose_name='Reported defect'),
        ),
        migrations.AddField(
            model_name='defect',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_defect_related', related_query_name='defect_defects', to=settings.DEFECT_AREA_MODEL, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_defect_related', related_query_name='defect_defects', to=settings.DEFECT_DEFECTTYPE_MODEL, verbose_name='Defect type'),
        ),
        migrations.AddField(
            model_name='defect',
            name='visible_groups',
            field=models.ManyToManyField(blank=True, related_name='defect_defect_related', related_query_name='defect_defects', to='auth.Group', verbose_name='Visible groups'),
        ),
        migrations.AddField(
            model_name='area',
            name='visible_groups',
            field=models.ManyToManyField(blank=True, related_name='defect_area_related', related_query_name='defect_areas', to='auth.Group', verbose_name='Visible groups'),
        ),
    ]
