# Generated by Django 3.1.2 on 2020-11-26 16:32

from django.db import migrations, models
import src.components.content.news.model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titel')),
                ('text', models.TextField(verbose_name='Text')),
                ('document', models.FileField(blank=True, null=True, upload_to=src.components.content.news.model.news_document_dir)),
                ('href', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Link')),
                ('kind', models.CharField(choices=[('1', 'Information'), ('2', 'Angebot')], db_index=True, default='1', max_length=2, verbose_name='Art')),
                ('show_in_header', models.BooleanField(default=True, verbose_name='Im Header anzeigen')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Ab Datum')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Bis Datum')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Neuigkeit',
                'verbose_name_plural': 'Neuigkeiten',
                'ordering': ['order'],
            },
        ),
    ]
