# Generated by Django 3.1.2 on 2020-11-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_auto_20201127_1333'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='property',
            field=models.ManyToManyField(to='real_estate.Property', verbose_name='Sichbar für Properties'),
        ),
    ]
