# Generated by Django 3.1.2 on 2020-12-01 14:44

from django.db import migrations, models
import src.components.content.news.model


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_auto_20201127_1333'),
        ('content', '0002_news_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=src.components.content.news.model.news_document_dir, verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='news',
            name='property',
            field=models.ManyToManyField(blank=True, null=True, to='real_estate.Property', verbose_name='Sichbar für Properties'),
        ),
    ]
