# Generated by Django 3.1.4 on 2020-12-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20201201_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titel')),
                ('text', models.TextField(verbose_name='Text')),
                ('href', models.CharField(blank=True, max_length=256, null=True, verbose_name='URL')),
                ('group', models.CharField(max_length=150, verbose_name='Gruppe')),
                ('sorting', models.IntegerField(default=10, verbose_name='Sortierung?')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
