# Generated by Django 3.1.4 on 2020-12-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('content', '0004_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='visible_object',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name="Sichtbar für Objekt (Trennen mit ';')"),
        ),
        migrations.AddField(
            model_name='faq',
            name='visible_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
