# Generated by Django 3.1.4 on 2020-12-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20201221_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='group',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Gruppe'),
        ),
    ]
