# Generated by Django 3.1.5 on 2021-01-20 20:43

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import src.components.content.offers.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('content', '0006_auto_20201223_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titel')),
                ('text', models.TextField(verbose_name='Text')),
                ('icon', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=src.components.content.offers.models.marketplace_photo_dir)),
                ('website', models.CharField(max_length=250, verbose_name='Webseite')),
                ('hidden', models.BooleanField(default=False, verbose_name='Ausblenden')),
                ('only_login', models.BooleanField(default=True, verbose_name='Sichtbar für registrierte User')),
                ('only_guest', models.BooleanField(default=True, verbose_name='Sichtbar für nicht-registrierte User')),
                ('report_clickes', models.IntegerField(default=0)),
                ('sorting', models.IntegerField(default=0)),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Ab Datum')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Bis Datum')),
                ('visible_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'verbose_name': 'Angebot',
                'verbose_name_plural': 'Angebote',
            },
        ),
    ]
