# Generated by Django 3.1.5 on 2021-01-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150, verbose_name='slug')),
                ('html', models.TextField(default='<html></html>', verbose_name='HTML content')),
            ],
        ),
    ]
