# Generated by Django 3.1.5 on 2021-01-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='html',
            field=models.TextField(default='<html><body><h1>Please Change Me</h1></body></html>', verbose_name='HTML content'),
        ),
    ]
