# Generated by Django 3.1.5 on 2021-03-02 12:33

from django.db import migrations, models
import src.components.content.news.model


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20210129_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='document',
            field=models.FileField(blank=True, max_length=350, null=True, upload_to=src.components.content.news.model.news_document_dir, verbose_name='Dokument'),
        ),
    ]
