GET_TICKET_PROCESS_FIELDS_FIRST_STEP = {
    "DATA": [
        {
            "DEPENDENCY": {
                "COLUMNLIST": "CHECK_FIELD,CHECK_FIELD_OP,CHECK_VALUE,TARGET_FIELD,TARGET_FIELD_RAW,TARGET_PROCESSID,TARGET_TYPE,TARGET_VALUE",
                "ROWCOUNT": "0",
                "ROWS": [],
            },
            "DISABLED": False,
            "FIELD": "LABEL_Sie_wollen_Ihr",
            "GROUP": "",
            "HIDDEN": False,
            "LABEL": "&lt;p&gt;Sie wollen Ihren Wohnsitz ummelden, oder brauchen f&amp;uumlr andere Zwecke eine Wohnungsgeberbest&amp;aumltigung?&lt;\/p&gt;",
            "MAXLEN": "50",
            "PARAM1": "",
            "PARAM2": "",
            "REQUIRED": False,
            "TYPE": "label",
            "VALUE": "&lt;p&gt;Sie wollen Ihren Wohnsitz ummelden, oder brauchen f&amp;uumlr andere Zwecke eine Wohnungsgeberbest&amp;aumltigung?&lt;\/p&gt;",
        }
    ],
    "ERRORTEXT": "",
    "SUCCESS": True,
}

GET_TICKET_PROCESS_FIELDS_FIRST_STEP_TEST_INFO_TICKET = {
    "DATA": [
        {
            "DEPENDENCY": {
                "COLUMNLIST": "CHECK_FIELD,CHECK_FIELD_OP,CHECK_VALUE,TARGET_FIELD,TARGET_FIELD_RAW,TARGET_PROCESSID,TARGET_TYPE,TARGET_VALUE",
                "ROWCOUNT": "0",
                "ROWS": [],
            },
            "DISABLED": False,
            "FIELD": "LABEL_Bitte_pr_uu150",
            "GROUP": "",
            "HIDDEN": False,
            "LABEL": "&lt;p&gt;Bitte pr&amp;uuml;fen Sie, ob es sich um einen Selbstzahler oder ein SEPA-Mandat handelt.&amp;nbsp;&lt;\/p&gt;&lt;p&gt;Verwenden Sie ggf. ein Folgeticket, um Informationen vom Kundenbetreuer einzuholen.&amp;nbsp;&lt;\/p&gt;&lt;p&gt;Im Falle des SEPA:&lt;\/p&gt;&lt;p&gt;Bitte pr&amp;uuml;fen Sie, ob das SEPA-Mandat richtig bzw. vollst&amp;auml;ndig angelegt wurde.&lt;\/p&gt;&lt;p&gt;Bei korrekter Abbuchung, w&amp;auml;hlen Sie den Button &amp;quot;&lt;strong&gt;Abbuchung korrekt&lt;\/strong&gt;&amp;quot;.&lt;\/p&gt;&lt;p&gt;Bei fehlerhafter \/ nicht erfolgter Abbuchung, w&amp;auml;hlen Sie den Button &amp;quot;&lt;strong&gt;Abbuchung fehlerhaft&lt;\/strong&gt;&amp;quot;.&lt;\/p&gt;&lt;p&gt;Im Falle Selbstzahler, teilen Sie dies dem Mieter entsprechend mit.&amp;nbsp;&lt;\/p&gt;",
            "MAXLEN": "50",
            "PARAM1": "",
            "PARAM2": "",
            "REQUIRED": False,
            "TYPE": "label",
            "VALUE": "&lt;p&gt;Bitte pr&amp;uuml;fen Sie, ob es sich um einen Selbstzahler oder ein SEPA-Mandat handelt.&amp;nbsp;&lt;\/p&gt;&lt;p&gt;Verwenden Sie ggf. ein Folgeticket, um Informationen vom Kundenbetreuer einzuholen.&amp;nbsp;&lt;\/p&gt;&lt;p&gt;Im Falle des SEPA:&lt;\/p&gt;&lt;p&gt;Bitte pr&amp;uuml;fen Sie, ob das SEPA-Mandat richtig bzw. vollst&amp;auml;ndig angelegt wurde.&lt;\/p&gt;&lt;p&gt;Bei korrekter Abbuchung, w&amp;auml;hlen Sie den Button &amp;quot;&lt;strong&gt;Abbuchung korrekt&lt;\/strong&gt;&amp;quot;.&lt;\/p&gt;&lt;p&gt;Bei fehlerhafter \/ nicht erfolgter Abbuchung, w&amp;auml;hlen Sie den Button &amp;quot;&lt;strong&gt;Abbuchung fehlerhaft&lt;\/strong&gt;&amp;quot;.&lt;\/p&gt;&lt;p&gt;Im Falle Selbstzahler, teilen Sie dies dem Mieter entsprechend mit.&amp;nbsp;&lt;\/p&gt;",
        },
        {
            "DEPENDENCY": {
                "COLUMNLIST": "CHECK_FIELD,CHECK_FIELD_OP,CHECK_VALUE,TARGET_FIELD,TARGET_FIELD_RAW,TARGET_PROCESSID,TARGET_TYPE,TARGET_VALUE",
                "ROWCOUNT": "0",
                "ROWS": [],
            },
            "DISABLED": False,
            "FIELD": "SAP_Individualsch130",
            "GROUP": "",
            "HIDDEN": False,
            "LABEL": "Individualschreiben",
            "MAXLEN": "50",
            "PARAM1": "",
            "PARAM2": "",
            "REQUIRED": False,
            "TYPE": "sap",
            "VALUE": "*",
        },
        {
            "DEPENDENCY": {
                "COLUMNLIST": "CHECK_FIELD,CHECK_FIELD_OP,CHECK_VALUE,TARGET_FIELD,TARGET_FIELD_RAW,TARGET_PROCESSID,TARGET_TYPE,TARGET_VALUE",
                "ROWCOUNT": "0",
                "ROWS": [],
            },
            "DISABLED": False,
            "FIELD": "CHECKBOX_Alles_erld1",
            "GROUP": "",
            "HIDDEN": False,
            "LABEL": "Alles erledigt?",
            "MAXLEN": "50",
            "PARAM1": "",
            "PARAM2": "",
            "REQUIRED": True,
            "TYPE": "checkbox",
            "VALUE": "",
        },
        {
            "DEPENDENCY": {
                "COLUMNLIST": "CHECK_FIELD,CHECK_FIELD_OP,CHECK_VALUE,TARGET_FIELD,TARGET_FIELD_RAW,TARGET_PROCESSID,TARGET_TYPE,TARGET_VALUE",
                "ROWCOUNT": "62",
                "ROWS": [
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Stromgutschrift ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "Hinweis: BTS-Kontierung ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Instandhaltung ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "Hinweis: BTS-Kontierung ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Elektroherd (Bestandmieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "Hinweis: Bestandsmieter ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Elektroherd (Neumieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "Hinweis: Neumieter ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Materialkosten (Bestandsmieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "Hinweis: Bestandsmieter ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Materialkosten (Neumieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "Hinweis: Neumieter ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Telefon\/Internetkosten (Bestandsmieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "Hinweis: Bestandsmieter ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Telefon\/Internetkosten (Neumieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "Hinweis: Neumieter ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Schlüsseldienst (Bestandsmieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "Hinweis: Bestandsmieter ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Schlüsseldienst (Neumieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "Hinweis: Neumieter ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Anwaltskosten Gebäudehaftpflicht ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "Hinweis: Abstimmung mit ZFM! ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Anwaltskosten  Kosten für Miet- und Räumungsklagen ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "Hinweis: Abstimmung mit ZFM! ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Anwaltskosten Gerichtskosten ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "Hinweis: Abstimmung mit ZFM! ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Anwaltskosten Vollstreckungskosten ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "Hinweis: Abstimmung mit ZFM! ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Stromgutschrift ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SHOW                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Instandhaltung ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SHOW                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Elektroherd (Bestandmieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SHOW                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Elektroherd (Neumieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SHOW                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Materialkosten (Bestandsmieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SHOW                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Materialkosten (Neumieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SHOW                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Telefon\/Internetkosten (Bestandsmieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SHOW                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Telefon\/Internetkosten (Neumieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SHOW                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Schlüsseldienst (Bestandsmieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SHOW                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Schlüsseldienst (Neumieter) ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SHOW                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Anwaltskosten Gebäudehaftpflicht ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SHOW                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Anwaltskosten  Kosten für Miet- und Räumungsklagen ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SHOW                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Anwaltskosten Gerichtskosten ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SHOW                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Anwaltskosten Vollstreckungskosten ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SHOW                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Personenschaden durch Gebäudemangel ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "HIDE                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Personenschaden durch Dienstleistermangel ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "HIDE                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Personenschaden durch fehlende Beauftragung Dienstleister ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "HIDE                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Personenschaden allgemein ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "HIDE                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Umzugskosten ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "HIDE                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Lagerkosten ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "HIDE                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Kosten für Ausweichunterkunft ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "HIDE                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Parkkosten ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "HIDE                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Ersatzkosten ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "HIDE                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Sachschaden ",
                        "TARGET_FIELD": "valLABEL_Sachkonto1.Ticket ",
                        "TARGET_FIELD_RAW": "LABEL_Sachkonto1     ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "HIDE                                               ",
                        "TARGET_VALUE": " ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Personenschaden durch Gebäudemangel ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "2522 0000 Versicherungsforderung ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Personenschaden durch Dienstleistermangel ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "Schadensersatzforderung ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Personenschaden durch fehlende Beauftragung Dienstleister ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "2522 0000 Versicherungsforderung ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Personenschaden allgemein ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8087 0000 Sonstige Aufwendungen HBW ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Umzugskosten ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8087 0000 Sonstige Aufwendungen HBW ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Lagerkosten ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8087 0000 Sonstige Aufwendungen HBW ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Stromgutschrift ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "siehe Instandhaltungsplan \/ BTS-Kontierung ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Kosten für Ausweichunterkunft ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8087 0000 Sonstige Aufwendungen HBW ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Instandhaltung ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "siehe Instandhaltungsplan \/ BTS-Kontierung ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Elektroherd (Bestandmieter) ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8050 7670 (Elektro) bei laufendem MV ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Elektroherd (Neumieter) ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8050 7970 (Elektro) bei Neuvermietung ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Materialkosten (Bestandsmieter) ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8050 7646 (Tapezier-\/Malerarbeiten Whg.) bei laufendem MV ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Materialkosten (Neumieter) ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8050 7946 (Tapezier-\/Malerarbeiten Whg.) bei Neuvermietung ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Telefon\/Internetkosten (Bestandsmieter) ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8050 7680 (Innenausbau) bei laufendem MV ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Telefon\/Internetkosten (Neumieter) ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8050 7980 (Innenausbau) bei Neuvermietung ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Schlüsseldienst (Bestandsmieter) ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8050 7683 (Schreinerarbeiten, Türen, Schlösser, Zylinder) bei laufendem MV ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Schlüsseldienst (Neumieter) ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8050 7983 (Schreinerarbeiten, Türen, Schlösser, Zylinder) bei Neuvermietung ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Parkkosten ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8087 0000 Sonstige Aufwendungen HBW ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Ersatzkosten ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8087 0000 Sonstige Aufwendungen HBW ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Sachschaden ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "2522 0000 Versicherungsforderung ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Anwaltskosten Gebäudehaftpflicht ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8091 0000 Kosten für Miet- und Räumungsklagen ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Anwaltskosten  Kosten für Miet- und Räumungsklagen ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8091 0100 Anwaltskosten ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Anwaltskosten Gerichtskosten ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8091 0200 Gerichtskosten ",
                    },
                    {
                        "CHECK_FIELD": "SEFCOMBO_Auswahl_Sh1 ",
                        "CHECK_FIELD_OP": "=          ",
                        "CHECK_VALUE": "Anwaltskosten Vollstreckungskosten ",
                        "TARGET_FIELD": "valSEFCOMBO_Sachkonto 9.Ticket ",
                        "TARGET_FIELD_RAW": "SEFCOMBO_Sachkonto 9 ",
                        "TARGET_PROCESSID": "20200519135200001221 ",
                        "TARGET_TYPE": "SET_VALUE_EVER                                     ",
                        "TARGET_VALUE": "8091 0300 Vollstreckungskosten ",
                    },
                ],
            },
            "DISABLED": False,
            "FIELD": "SEFCOMBO_Auswahl_Sh1",
            "GROUP": "",
            "HIDDEN": False,
            "LABEL": "Auswahl Schadensfall",
            "MAXLEN": "50",
            "PARAM1": {
                "COLUMNLIST": "KURZTEXT,LANGTEXT",
                "ROWCOUNT": "25",
                "ROWS": [
                    {"KURZTEXT": "* ", "LANGTEXT": "* "},
                    {
                        "KURZTEXT": "Anwaltskosten  Kosten für Miet- und Räumungsklagen ",
                        "LANGTEXT": "Anwaltskosten  Kosten für Miet- und Räumungsklagen ",
                    },
                    {
                        "KURZTEXT": "Anwaltskosten Gebäudehaftpflicht ",
                        "LANGTEXT": "Anwaltskosten Gebäudehaftpflicht ",
                    },
                    {
                        "KURZTEXT": "Anwaltskosten Gerichtskosten ",
                        "LANGTEXT": "Anwaltskosten Gerichtskosten ",
                    },
                    {
                        "KURZTEXT": "Anwaltskosten Vollstreckungskosten ",
                        "LANGTEXT": "Anwaltskosten Vollstreckungskosten ",
                    },
                    {
                        "KURZTEXT": "Elektroherd (Bestandmieter) ",
                        "LANGTEXT": "Elektroherd (Bestandmieter) ",
                    },
                    {
                        "KURZTEXT": "Elektroherd (Neumieter) ",
                        "LANGTEXT": "Elektroherd (Neumieter) ",
                    },
                    {"KURZTEXT": "Ersatzkosten ", "LANGTEXT": "Ersatzkosten "},
                    {"KURZTEXT": "Instandhaltung ", "LANGTEXT": "Instandhaltung "},
                    {
                        "KURZTEXT": "Kosten für Ausweichunterkunft ",
                        "LANGTEXT": "Kosten für Ausweichunterkunft ",
                    },
                    {"KURZTEXT": "Lagerkosten ", "LANGTEXT": "Lagerkosten "},
                    {
                        "KURZTEXT": "Materialkosten (Bestandsmieter) ",
                        "LANGTEXT": "Materialkosten (Bestandsmieter) ",
                    },
                    {
                        "KURZTEXT": "Materialkosten (Neumieter) ",
                        "LANGTEXT": "Materialkosten (Neumieter) ",
                    },
                    {"KURZTEXT": "Parkkosten ", "LANGTEXT": "Parkkosten "},
                    {
                        "KURZTEXT": "Personenschaden allgemein ",
                        "LANGTEXT": "Personenschaden allgemein ",
                    },
                    {
                        "KURZTEXT": "Personenschaden durch Dienstleistermangel ",
                        "LANGTEXT": "Personenschaden durch Dienstleistermangel ",
                    },
                    {
                        "KURZTEXT": "Personenschaden durch Gebäudemangel ",
                        "LANGTEXT": "Personenschaden durch Gebäudemangel ",
                    },
                    {
                        "KURZTEXT": "Personenschaden durch fehlende Beauftragung Dienst ",
                        "LANGTEXT": "Personenschaden durch fehlende Beauftragung Dienstleister ",
                    },
                    {"KURZTEXT": "Sachschaden ", "LANGTEXT": "Sachschaden "},
                    {
                        "KURZTEXT": "Schlüsseldienst (Bestandsmieter) ",
                        "LANGTEXT": "Schlüsseldienst (Bestandsmieter) ",
                    },
                    {
                        "KURZTEXT": "Schlüsseldienst (Neumieter) ",
                        "LANGTEXT": "Schlüsseldienst (Neumieter) ",
                    },
                    {"KURZTEXT": "Stromgutschrift ", "LANGTEXT": "Stromgutschrift "},
                    {
                        "KURZTEXT": "Telefon\/Internetkosten (Bestandsmieter) ",
                        "LANGTEXT": "Telefon\/Internetkosten (Bestandsmieter) ",
                    },
                    {
                        "KURZTEXT": "Telefon\/Internetkosten (Neumieter) ",
                        "LANGTEXT": "Telefon\/Internetkosten (Neumieter) ",
                    },
                    {"KURZTEXT": "Umzugskosten ", "LANGTEXT": "Umzugskosten "},
                ],
            },
            "PARAM2": "",
            "REQUIRED": True,
            "TYPE": "sefcombo",
            "VALUE": "",
        },
        {
            "DEPENDENCY": {
                "COLUMNLIST": "CHECK_FIELD,CHECK_FIELD_OP,CHECK_VALUE,TARGET_FIELD,TARGET_FIELD_RAW,TARGET_PROCESSID,TARGET_TYPE,TARGET_VALUE",
                "ROWCOUNT": "0",
                "ROWS": [],
            },
            "DISABLED": False,
            "FIELD": "LABEL_Sachkonto1",
            "GROUP": "",
            "HIDDEN": False,
            "LABEL": "&lt;p&gt;Hinweis&lt;\/p&gt;",
            "MAXLEN": "50",
            "PARAM1": "",
            "PARAM2": "",
            "REQUIRED": False,
            "TYPE": "label",
            "VALUE": "&lt;p&gt;Hinweis&lt;\/p&gt;",
        },
        {
            "DEPENDENCY": {
                "COLUMNLIST": "CHECK_FIELD,CHECK_FIELD_OP,CHECK_VALUE,TARGET_FIELD,TARGET_FIELD_RAW,TARGET_PROCESSID,TARGET_TYPE,TARGET_VALUE",
                "ROWCOUNT": "0",
                "ROWS": [],
            },
            "DISABLED": True,
            "FIELD": "SEFCOMBO_Sachkonto 9",
            "GROUP": "",
            "HIDDEN": False,
            "LABEL": "Sachkonto",
            "MAXLEN": "200",
            "PARAM1": "",
            "PARAM2": "",
            "REQUIRED": False,
            "TYPE": "text",
            "VALUE": "",
        },
    ],
    "ERRORTEXT": "",
    "SUCCESS": True,
}


def GET_TICKET_PROCESS_FIELDS_FIRST_STEP_TEST_INFO_TICKET_NORMALIZED():
    return {
        "data": {
            "issue": {
                "description": "<p>Bitte pr&uuml;fen Sie, ob es sich um einen Selbstzahler oder ein SEPA-Mandat handelt.&nbsp;<\\/p><p>Verwenden Sie ggf. ein Folgeticket, um Informationen vom Kundenbetreuer einzuholen.&nbsp;<\\/p><p>Im Falle des SEPA:<\\/p><p>Bitte pr&uuml;fen Sie, ob das SEPA-Mandat richtig bzw. vollst&auml;ndig angelegt wurde.<\\/p><p>Bei korrekter Abbuchung, w&auml;hlen Sie den Button &quot;<strong>Abbuchung korrekt<\\/strong>&quot;.<\\/p><p>Bei fehlerhafter \\/ nicht erfolgter Abbuchung, w&auml;hlen Sie den Button &quot;<strong>Abbuchung fehlerhaft<\\/strong>&quot;.<\\/p><p>Im Falle Selbstzahler, teilen Sie dies dem Mieter entsprechend mit.&nbsp;<\\/p>"
            },
            "questions": [
                {
                    "type": "-1",
                    "question": "Individualschreiben",
                    "required": False,
                    "code": "SAP_Individualsch130",
                },
                {
                    "type": "4",
                    "question": "Alles erledigt?",
                    "required": True,
                    "code": "CHECKBOX_Alles_erld1",
                },
                {
                    "type": "5",
                    "question": "Auswahl Schadensfall",
                    "multi": False,
                    "answers": "*;Anwaltskosten  Kosten für Miet- und Räumungsklagen;Anwaltskosten Gebäudehaftpflicht;Anwaltskosten Gerichtskosten;Anwaltskosten Vollstreckungskosten;Elektroherd (Bestandmieter);Elektroherd (Neumieter);Ersatzkosten;Instandhaltung;Kosten für Ausweichunterkunft;Lagerkosten;Materialkosten (Bestandsmieter);Materialkosten (Neumieter);Parkkosten;Personenschaden allgemein;Personenschaden durch Dienstleistermangel;Personenschaden durch Gebäudemangel;Personenschaden durch fehlende Beauftragung Dienst;Sachschaden;Schlüsseldienst (Bestandsmieter);Schlüsseldienst (Neumieter);Stromgutschrift;Telefon\\/Internetkosten (Bestandsmieter);Telefon\\/Internetkosten (Neumieter);Umzugskosten",
                    "required": True,
                    "code": "SEFCOMBO_Auswahl_Sh1",
                },
                {
                    "type": "1",
                    "question": "Sachkonto",
                    "required": False,
                    "code": "SEFCOMBO_Sachkonto 9",
                },
            ],
        },
        "error": "",
        "success": True,
    }
