GET_KEYWORDS = {
    "DATA": {
        "COLUMNLIST": "CATEGORY,DESCRIPTION,KEYWORD,PROCESS,TICKETGROUP,TICKETTYPE",
        "ROWCOUNT": "27",
        "ROWS": [
            {
                "CATEGORY": "Allgemeine Auskünfte",
                "DESCRIPTION": "",
                "KEYWORD": "Mieter App: Anforderung einer Mietbescheinigung",
                "PROCESS": "Allgemeine Auskünfte",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Wohnungsgeberbestätigung",
                "DESCRIPTION": "",
                "KEYWORD": "Mieter App: Anforderung einer Wohnungsgeberbestätigung",
                "PROCESS": "Wohnungsgeberbestätigung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Anpassung Vorauszahlung",
                "DESCRIPTION": "",
                "KEYWORD": "Mieter App: Anpassung Ihrer Nebenkostenvorauszahlung",
                "PROCESS": "Anpassung Vorauszahlung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Änderung Stammdaten",
                "DESCRIPTION": "",
                "KEYWORD": "Mieter App: Aufnahme weiterer Personen in Ihren Mietvertrag",
                "PROCESS": "Änderung Stammdaten",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Auszahlung Guthaben",
                "DESCRIPTION": "",
                "KEYWORD": "Mieter App: Auszahlung Guthaben",
                "PROCESS": "Auszahlung Guthaben",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Ratenzahlungsvereinbarung",
                "DESCRIPTION": "",
                "KEYWORD": "Mieter App: Beantragung einer Ratenzahlungsvereinbarung",
                "PROCESS": "Ratenzahlungsvereinbarung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Genehmigung",
                "DESCRIPTION": "",
                "KEYWORD": "Mieter App: Genehmigung zur Tierhaltung",
                "PROCESS": "Genehmigung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Genehmigung",
                "DESCRIPTION": "",
                "KEYWORD": "Mieter App: Genehmigung zur Untervermietung",
                "PROCESS": "Genehmigung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Allgemeine Auskünfte",
                "DESCRIPTION": "",
                "KEYWORD": "Mieter App: Schlüsselbestellung",
                "PROCESS": "Schlüssel- \/Zylinderbestellung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Kündigung - Miete",
                "DESCRIPTION": "",
                "KEYWORD": "Mieter App: Vorschlag eines Nachmieters",
                "PROCESS": "Vorschlag Nachmieter",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Bankverbindung",
                "DESCRIPTION": "",
                "KEYWORD": "Mieter App: Änderung Ihrer Bankverbindung",
                "PROCESS": "Bankverbindung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Test",
                "DESCRIPTION": "Testbeschreibung",
                "KEYWORD": "TEST - Info",
                "PROCESS": "Corona",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Demo",
                "DESCRIPTION": "",
                "KEYWORD": "Test Infoticket",
                "PROCESS": "Abbuchung Miete fehlerhaft",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Allgemeine Auskünfte",
                "DESCRIPTION": "",
                "KEYWORD": "W Anforderung Mietbescheinigung",
                "PROCESS": "Allgemeine Auskünfte",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Auszahlung Guthaben",
                "DESCRIPTION": "",
                "KEYWORD": "W Auszahlung Guthaben",
                "PROCESS": "Auszahlung Guthaben",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Genehmigung",
                "DESCRIPTION": "",
                "KEYWORD": "W Genehmigung Kleintier",
                "PROCESS": "Genehmigung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Genehmigung",
                "DESCRIPTION": "",
                "KEYWORD": "W Genehmigung Untermieter",
                "PROCESS": "Genehmigung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Genehmigung",
                "DESCRIPTION": "",
                "KEYWORD": "W Hundgenehmigung",
                "PROCESS": "Genehmigung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Genehmigung",
                "DESCRIPTION": "",
                "KEYWORD": "W Katzengenehmigung",
                "PROCESS": "Genehmigung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Neuer Mietvertrag Miete",
                "DESCRIPTION": "",
                "KEYWORD": "W Nachmieter",
                "PROCESS": "Vorschlag Nachmieter",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Bankverbindung",
                "DESCRIPTION": "",
                "KEYWORD": "W Neue Bankverbindung \/ Änderung Bankverbindung",
                "PROCESS": "Bankverbindung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Änderung Stammdaten",
                "DESCRIPTION": "",
                "KEYWORD": "W Person in Mietvertrag aufnehmen",
                "PROCESS": "Änderung Stammdaten",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Ratenzahlungsvereinbarung",
                "DESCRIPTION": "",
                "KEYWORD": "W Ratenzahlungsvereinbarung",
                "PROCESS": "Ratenzahlungsvereinbarung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Diverse Anliegen",
                "DESCRIPTION": "",
                "KEYWORD": "W Schlüssel- \/ Zylinderbestellung",
                "PROCESS": "Schlüssel- \/Zylinderbestellung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Anpassung Vorauszahlung",
                "DESCRIPTION": "",
                "KEYWORD": "W Vorauszahlung anpassen",
                "PROCESS": "Anpassung Vorauszahlung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "Allgemeine Auskünfte",
                "DESCRIPTION": "",
                "KEYWORD": "W Wohnungsgeberbestätigung",
                "PROCESS": "Wohnungsgeberbestätigung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
            {
                "CATEGORY": "WEG Schlüssel- \/ Zylinderbestellung",
                "DESCRIPTION": "",
                "KEYWORD": "WEG Schlüssel- \/ Zylinderbestellung",
                "PROCESS": "WEG Schlüssel- \/ Zylinderbestellung",
                "TICKETGROUP": "",
                "TICKETTYPE": "PROCESS",
            },
        ],
    },
    "ERRORTEXT": "",
    "SUCCESS": True,
}


def GET_KEYWORD_NORMALIZED():
    return {
        "data": {
            "issues": [
                {
                    "group": None,
                    "code": "Mieter App: Anforderung einer Mietbescheinigung",
                    "title": "Allgemeine Auskünfte",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "Mieter App: Anforderung einer Wohnungsgeberbestätigung",
                    "title": "Wohnungsgeberbestätigung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "Mieter App: Anpassung Ihrer Nebenkostenvorauszahlung",
                    "title": "Anpassung Vorauszahlung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "Mieter App: Aufnahme weiterer Personen in Ihren Mietvertrag",
                    "title": "Änderung Stammdaten",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "Mieter App: Auszahlung Guthaben",
                    "title": "Auszahlung Guthaben",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "Mieter App: Beantragung einer Ratenzahlungsvereinbarung",
                    "title": "Ratenzahlungsvereinbarung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "Mieter App: Genehmigung zur Tierhaltung",
                    "title": "Genehmigung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "Mieter App: Genehmigung zur Untervermietung",
                    "title": "Genehmigung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "Mieter App: Schlüsselbestellung",
                    "title": "Schlüssel- \\/Zylinderbestellung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "Mieter App: Vorschlag eines Nachmieters",
                    "title": "Vorschlag Nachmieter",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "Mieter App: Änderung Ihrer Bankverbindung",
                    "title": "Bankverbindung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "TEST - Info",
                    "title": "Corona",
                    "type": "Testbeschreibung",
                },
                {
                    "group": None,
                    "code": "Test Infoticket",
                    "title": "Abbuchung Miete fehlerhaft",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "W Anforderung Mietbescheinigung",
                    "title": "Allgemeine Auskünfte",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "W Auszahlung Guthaben",
                    "title": "Auszahlung Guthaben",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "W Genehmigung Kleintier",
                    "title": "Genehmigung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "W Genehmigung Untermieter",
                    "title": "Genehmigung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "W Hundgenehmigung",
                    "title": "Genehmigung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "W Katzengenehmigung",
                    "title": "Genehmigung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "W Nachmieter",
                    "title": "Vorschlag Nachmieter",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "W Neue Bankverbindung \\/ Änderung Bankverbindung",
                    "title": "Bankverbindung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "W Person in Mietvertrag aufnehmen",
                    "title": "Änderung Stammdaten",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "W Ratenzahlungsvereinbarung",
                    "title": "Ratenzahlungsvereinbarung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "W Schlüssel- \\/ Zylinderbestellung",
                    "title": "Schlüssel- \\/Zylinderbestellung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "W Vorauszahlung anpassen",
                    "title": "Anpassung Vorauszahlung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "W Wohnungsgeberbestätigung",
                    "title": "Wohnungsgeberbestätigung",
                    "type": "",
                },
                {
                    "group": None,
                    "code": "WEG Schlüssel- \\/ Zylinderbestellung",
                    "title": "WEG Schlüssel- \\/ Zylinderbestellung",
                    "type": "",
                },
            ]
        },
        "error": "",
        "success": True,
    }
