# Generated by Django 3.1.4 on 2020-12-23 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import src.components.issues.issue.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Gruppe')),
                ('display_location', models.IntegerField(choices=[(1, 'Anliegen'), (2, 'Dokumente')], default=1)),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('html', models.TextField(default='<html></html>', verbose_name='HTML, erstellt mit: www.pdftohtml.net')),
                ('background', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=src.components.issues.issue.models.formular_background_dir)),
                ('background2', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=src.components.issues.issue.models.formular_background_dir)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=src.components.issues.issue.models.formular_document_dir, verbose_name='Anhang')),
                ('version', models.CharField(db_index=True, default='1.0', max_length=100, verbose_name='Version')),
                ('signing_type', models.CharField(blank=True, choices=[('digi', 'digital'), ('orig', 'original')], max_length=4, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('sorting', models.IntegerField(default=1, verbose_name='Position')),
                ('codegrp', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Codegruppe')),
                ('code', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Code')),
                ('sapkind', models.CharField(blank=True, db_index=True, default='IV', max_length=100, null=True, verbose_name='Meldungsart')),
                ('visible_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'verbose_name': 'Formular PDF',
                'verbose_name_plural': 'Formulare PDF',
            },
        ),
        migrations.CreateModel(
            name='IssueRequested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('answers', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True, verbose_name='Status')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues.issue', verbose_name='Anliegen')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Angefordertes Formular',
                'verbose_name_plural': 'Angeforderte Formulare',
            },
        ),
        migrations.CreateModel(
            name='IssueAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_index=True, max_length=150, verbose_name='Frage')),
                ('type', models.CharField(choices=[('1', 'Text'), ('2', 'Datum'), ('3', 'Zeit'), ('4', 'Ja/Nein'), ('5', 'Multiple Choice'), ('6', 'Multiple Choice Mehrfachauswahl'), ('7', 'Telefonnummer'), ('8', 'Zahl'), ('9', 'Welcher Vertragspartner')], db_index=True, default='1', max_length=2, verbose_name='Typ')),
                ('multi', models.BooleanField(default=False, verbose_name='Mehrfachauswahl bei Multiple Choice Fragen moeglich')),
                ('marker', models.CharField(db_index=True, max_length=100, verbose_name='Markierung in der HTML Vorlage')),
                ('answers', models.CharField(blank=True, db_index=True, max_length=1024, null=True, verbose_name="Auswahlmoeglichkeiten fuer MultipleChoice Fragen. Bitte Antworten mit ';' trennen.")),
                ('sorting', models.IntegerField(default=1, verbose_name='Position')),
                ('required', models.BooleanField(default=False, verbose_name='Antwort erforderlich')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.issue')),
            ],
            options={
                'verbose_name': 'Formular Antworten',
                'verbose_name_plural': 'Formulare Antworten',
            },
        ),
    ]
