# Generated by Django 3.1.4 on 2020-12-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20201229_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='sapkind',
            new_name='type',
        ),
    ]
