# Generated by Django 3.1.4 on 2020-12-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issueanswer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerequested',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Identifier of external system'),
        ),
    ]
