# Generated by Django 3.1.5 on 2021-02-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issuerequested_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='issue',
            name='description_postman',
            field=models.TextField(blank=True, null=True, verbose_name='Postman Beschreibung'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='codegrp',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Codegruppe'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(blank=True, db_index=True, default='IV', max_length=200, null=True, verbose_name='Meldungsart'),
        ),
    ]
