from src.shared.settings_factory import SettingsFactory

SETTINGS_NAMESPACE = "DIT_ISSUE"

DEFAULTS = {"ISSUE_REQUESTED_CREATE_HANDLER": None}

IMPORT_STRINGS = ["ISSUE_REQUESTED_CREATE_HANDLER"]

REMOVED_SETTINGS = []

dit_issues_settings = SettingsFactory(
    SETTINGS_NAMESPACE, DEFAULTS, IMPORT_STRINGS, REMOVED_SETTINGS, None
)
