# Generated by Django 3.1.4 on 2020-12-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwg_tenant', '0003_auto_20201201_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtstag'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Wohnort'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vorname'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nachname'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobil Telefonnummer'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefonnummer'),
        ),
        migrations.AddField(
            model_name='user',
            name='principal_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Persönliche Haupt-Identifikationsnummer'),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Straße'),
        ),
        migrations.AddField(
            model_name='user',
            name='street_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Hausnummer'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Postleitzahl'),
        ),
    ]
