# Generated by Django 3.1.4 on 2020-12-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwg_tenant', '0004_auto_20201213_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gwg_partner',
        ),
    ]
