# Generated by Django 3.1.5 on 2021-03-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwg_tenant', '0005_remove_user_gwg_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_data_accepted',
            field=models.BooleanField(default=False, help_text='Designates whether this user has accepted the data privacy', verbose_name='data accepted'),
        ),
    ]
