# Generated by Django 3.1.5 on 2021-03-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwg_tenant', '0006_user_is_data_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Code'),
        ),
    ]
