# Generated by Django 3.1.5 on 2021-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwg_tenant', '0007_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_contract',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address change contract'),
        ),
    ]
