# Generated by Django 3.1.5 on 2021-04-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwg_tenant', '0008_user_email_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Hausnummer'),
        ),
    ]
