# Generated by Django 3.1.5 on 2021-05-19 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Umfrage')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('text2', models.TextField(blank=True, null=True, verbose_name='Schlusswort')),
                ('dialog', models.CharField(max_length=512, verbose_name='Nachricht in Dialog')),
                ('visible_object', models.CharField(blank=True, max_length=1024, null=True, verbose_name="Sichtbar für Objekt (Trennen mit ';')")),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Ab Datum')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Bis Datum')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktiv')),
                ('member', models.IntegerField(default=0, verbose_name='Teilnehmer insgesamt')),
            ],
            options={
                'verbose_name': 'Umfrage',
                'verbose_name_plural': 'Umfragen',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Frage')),
                ('multi', models.BooleanField(default=False, verbose_name='Mehrfachauswahl bei Multiple Choice Fragen moeglich')),
                ('sorting', models.IntegerField(default=0, verbose_name='Position')),
                ('answer1', models.CharField(blank=True, max_length=512, null=True, verbose_name='Antwort 1.')),
                ('type1', models.CharField(choices=[('1', 'Ankreuzen'), ('2', 'Text'), ('3', 'Zahl'), ('4', 'Range')], db_index=True, max_length=2, verbose_name='Typ Frage 1.')),
                ('count1', models.IntegerField(default=0, verbose_name='Antwort 1. gewählt')),
                ('answer2', models.CharField(blank=True, max_length=512, null=True, verbose_name='Antwort 2.')),
                ('type2', models.CharField(blank=True, choices=[('1', 'Ankreuzen'), ('2', 'Text'), ('3', 'Zahl'), ('4', 'Range')], db_index=True, max_length=2, null=True, verbose_name='Typ Frage 2.')),
                ('count2', models.IntegerField(default=0, verbose_name='Antwort 2. gewählt')),
                ('answer3', models.CharField(blank=True, max_length=512, null=True, verbose_name='Antwort 3.')),
                ('type3', models.CharField(blank=True, choices=[('1', 'Ankreuzen'), ('2', 'Text'), ('3', 'Zahl'), ('4', 'Range')], db_index=True, max_length=2, null=True, verbose_name='Typ Frage 3.')),
                ('count3', models.IntegerField(default=0, verbose_name='Antwort 3. gewählt')),
                ('answer4', models.CharField(blank=True, max_length=512, null=True, verbose_name='Antwort 4.')),
                ('type4', models.CharField(blank=True, choices=[('1', 'Ankreuzen'), ('2', 'Text'), ('3', 'Zahl'), ('4', 'Range')], db_index=True, max_length=2, null=True, verbose_name='Typ Frage 4.')),
                ('count4', models.IntegerField(default=0, verbose_name='Antwort 4. gewählt')),
                ('answer5', models.CharField(blank=True, max_length=512, null=True, verbose_name='Antwort 5.')),
                ('type5', models.CharField(blank=True, choices=[('1', 'Ankreuzen'), ('2', 'Text'), ('3', 'Zahl'), ('4', 'Range')], db_index=True, max_length=2, null=True, verbose_name='Typ Frage 5.')),
                ('count5', models.IntegerField(default=0, verbose_name='Antwort 5. gewählt')),
                ('answer6', models.CharField(blank=True, max_length=512, null=True, verbose_name='Antwort 6.')),
                ('type6', models.CharField(blank=True, choices=[('1', 'Ankreuzen'), ('2', 'Text'), ('3', 'Zahl'), ('4', 'Range')], db_index=True, max_length=2, null=True, verbose_name='Typ Frage 6.')),
                ('count6', models.IntegerField(default=0, verbose_name='Antwort 6. gewählt')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.survey')),
            ],
            options={
                'verbose_name': 'Umfrage Frage',
                'verbose_name_plural': 'Umfrage Fragen',
            },
        ),
        migrations.CreateModel(
            name='SurveyMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.survey')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Umfragen Teilnehmer',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswersText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.TextField(blank=True, null=True, verbose_name='zu Antwort 1.')),
                ('answer2', models.TextField(blank=True, null=True, verbose_name='zu Antwort 2.')),
                ('answer3', models.TextField(blank=True, null=True, verbose_name='zu Antwort 3.')),
                ('answer4', models.TextField(blank=True, null=True, verbose_name='zu Antwort 4.')),
                ('answer5', models.TextField(blank=True, null=True, verbose_name='zu Antwort 5.')),
                ('answer6', models.TextField(blank=True, null=True, verbose_name='zu Antwort 6.')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.surveyquestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Umfrage Textantwort der Mieter',
            },
        ),
    ]
