# Generated by Django 3.1.2 on 2020-11-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_code', models.IntegerField(default=0, verbose_name='Buchungskreis')),
                ('entity', models.IntegerField(default=0, verbose_name='Wirtschaftseinheit')),
                ('object', models.IntegerField(default=0, verbose_name='Gebäude')),
                ('street', models.CharField(blank=True, max_length=128, null=True, verbose_name='Straße')),
                ('number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Hausnummer')),
                ('zip', models.CharField(blank=True, max_length=128, null=True, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, default='Mannheim', max_length=128, null=True, verbose_name='Ort')),
                ('center', models.CharField(blank=True, max_length=128, null=True, verbose_name='KSC')),
            ],
            options={
                'verbose_name': 'Wirtschaftseinheit',
                'verbose_name_plural': 'Wirtschaftseinheiten',
            },
        ),
    ]
