# Generated by Django 3.1.2 on 2020-11-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Objekt', 'verbose_name_plural': 'Objekte'},
        ),
    ]
