# Generated by Django 3.1.4 on 2020-12-13 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0003_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_partners',
        ),
        migrations.AddField(
            model_name='contract',
            name='partners',
            field=models.ManyToManyField(related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
